### ISSUE TITLE
Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by juyeong1260** [chitacan/xprt#1]
`.babelrc` 또는 `.gitignore` 와 같은 단일 파일이 레포지토리의 루트에 위치할 때 `Error: spawn ENOTDIR` 가 발생합니다.

```
// example
root
  |-- app/
  |   |-- index.js
  |    -- utils.js
  |-- .babelrc
  |-- .gitignore
```

레포의 루트에 있는 단일 파일도 같이 `summary` 를 진행할 수 있는 방법이 있나요??

**Comment by saltylight** [comment]
@juyeong1260 
저는 이 에러 .DS_Store 때문에 뜨긴 했었습니다.
전 삭제해서 실행하긴 했지만 흠... 🤔

**Comment by juyeong1260** [comment]
@saltylight 흠.. 저는 `.DS_Store` 가 없었고, 단일파일에서 발생하는 에러인것 같아서 

```
home
  |-- riiid
        |---- master
```

이 구조에서 `home` 에서 `xprt git riiid` 를 실행해서 에러를 피하긴 했는데, 워크트리를 사용하는 경우에는 워크트리를 제거해야 해서 혹시 다른 방법이 있는지 궁금했습니다 🤔

결국 커밋리스트는 [octokit/rest](https://github.com/octokit/rest.js) 를 사용해서 불러왔는데 라인수는 제공하지 않아서 `xprt`를 사용했어요.

octokit/rest 를 사용한 cli 도 만들어보면 재밌을 것 같네용 ✋

**Comment by saltylight** [comment]
@juyeong1260 👍
`xprt`는 `git summary`를 쓰는데 git-extras에서 기간설정하는건 없어서 commit이랑 line을 기간설정해서 데이터를 뽑을 수 없더라구요. 혹시 생각해보신 띵크빅한 방법 없나욤 😶

**Comment by juyeong1260** [comment]
@saltylight 아뇸... ㅠㅠ `git-extras` 에서 어떻게 line 을 뽑는지 코드를 봐야겠네요..

커밋은 `octokit/rest` 의 [repo.getCommits](https://octokit.github.io/rest.js/#api-Repos-getCommits) 를 사용해서 기간 설정을 하여 불러왔습니다!

**Comment by chitacan** [comment]
@juyeong1260 @saltylight 일단 `.` 으로 시작되는 파일들 (`.bablerc`) 땜에 발생하는 [오류는 수정했습니다](https://github.com/chitacan/xprt/commit/721ffcba18ec6279c5d77ea5f4e38a3d13e3bfab) ✋

**Comment by chitacan** [comment]
`xprt git` 명령어에 대한 [설명도 업데이트 했습니다.](https://github.com/chitacan/xprt#git-repos_dir)
